# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62e9332b49f84545eafc9112ae7b1a09fa1f6182ef9ec3cdb2a117a1102ac07474ba5e71ba78ed9449904faf97de5d916edd7dda5c5709f665c77ba1b471cba7

test:
  secret_key_base: 47064f1b230c4272f821e5d0d9c69255133346a61a28e8765cdafebbdc31ca1c0f5d034b0c438a17751c82f20dee7472d78340fb0c6bd5c7359eb91fd6aef90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
